### ISSUE TITLE
[BUG]-Voltage Error running simulation

### ISSUE THREAD

**Issue by adurstewitz** [Shenzhen-Robotics-Alliance/maple-sim#58]
Getting the following error when starting gui simulation after updating to new maple-sim release.
```
Error at org.ironmaple.simulation.drivesims.SwerveModuleSimulation.getDriveMotorSupplyCurrent(SwerveModuleSimulation.java:215): Unhandled exception: java.lang.NoSuchMethodError: 'edu.wpi.first.units.measure.Dimensionless edu.wpi.first.units.measure.Voltage.div(edu.wpi.first.units.measure.Voltage)'
        at org.ironmaple.simulation.drivesims.SwerveModuleSimulation.getDriveMotorSupplyCurrent(SwerveModuleSimulation.java:215)
        at frc.robot.subsystems.drive.ModuleIOSim.updateInputs(ModuleIOSim.java:41)
        at frc.robot.subsystems.drive.Module.updateInputs(Module.java:59)
        at frc.robot.subsystems.drive.Drive.periodic(Drive.java:140)
        at edu.wpi.first.wpilibj2.command.CommandScheduler.run(CommandScheduler.java:263)
        at frc.robot.Robot.robotPeriodic(Robot.java:100)
        at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:400)
        at org.littletonrobotics.junction.LoggedRobot.startCompetition(LoggedRobot.java:121)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:418)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by catr1xLiu** [comment]
Thanks for reporting this issue! The problem is due to the API change in WPILib Beta 2.

Maple-sim v0.2.1 requires WPILib Beta 2. Upgrading WPILib should resolve the error.

However, there's no point in upgrading if you don't need WPILib Beta 2. The only change from v0.2.0 to v0.2.1 is the update to this specific API to be compatible with WPILib Beta 2.
