### ISSUE TITLE
[BUG]-MAXSwerve Module preset warns it is "abnormal"

### ISSUE THREAD

**Issue by nab138** [Shenzhen-Robotics-Alliance/maple-sim#70]
## Bug Description
When using `COTS.ofMAXSwerve(driveGearbox, turnGearbox, wheelCOF, gearRatioLevel)`, the robot code produces the following warnings (though the actual simulation seems to work fine):

```
Error at org.ironmaple.simulation.drivesims.configs.BoundingCheck.check(BoundingCheck.java:10): The provided "steer gear ratio" is 46.0times reduction, which seems abnormal, please check its correctness
        at org.ironmaple.simulation.drivesims.configs.BoundingCheck.check(BoundingCheck.java:10)
        at org.ironmaple.simulation.drivesims.SwerveModuleSimulation.<init>(SwerveModuleSimulation.java:111)
        at org.ironmaple.simulation.drivesims.COTS.lambda$ofMAXSwerve$8(COTS.java:302)
        ...
```
```
Error at org.ironmaple.simulation.drivesims.configs.BoundingCheck.check(BoundingCheck.java:10): The provided "drive wheel radius" is 1.4999999999999998inches, which seems abnormal, please check its correctness
        at org.ironmaple.simulation.drivesims.configs.BoundingCheck.check(BoundingCheck.java:10)
        at org.ironmaple.simulation.drivesims.SwerveModuleSimulation.<init>(SwerveModuleSimulation.java:114)
        at org.ironmaple.simulation.drivesims.COTS.lambda$ofMAXSwerve$8(COTS.java:302)
        ...
```

## Steps to Reproduce
Construct a `DriveTrainSimulationConfig` with a MAXSwerve module. E.x:
```java
public static final DriveTrainSimulationConfig mapleSimConfig = DriveTrainSimulationConfig.Default()
  .withCustomModuleTranslations(moduleTranslations)
  .withRobotMass(robotMassKg)
  .withGyro(COTS.ofNav2X())
  .withTrackLengthTrackWidth(Meters.of(wheelBase), Meters.of(trackWidth))
  .withSwerveModule(COTS.ofMAXSwerve(driveGearbox, turnGearbox, wheelCOF, 2));
 ```

**Comment by catr1xLiu** [comment]
This should fix it #73.
I'll make a release before kick-off.

**Comment by catr1xLiu** [comment]
New release will fix the problem

https://github.com/Shenzhen-Robotics-Alliance/maple-sim/releases/tag/v0.2.8
